name: tag-release
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Bump to v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Tag
        id: tag
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(echo ${MESSAGE} | cut -f 3 -d " ")
          echo "tag=${tag}" >> ${GITHUB_OUTPUT}
          echo Tagging ${tag}
          gh release create \
            ${tag} \
            --generate-notes
      - name: Upload addon zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -f \
            eslint.config.js \
            package.json \
            pnpm-lock.yaml

          cat manifest.json | jq 'del(.background.service_worker)' | tee manifest.json
          zip -r better-afreecatv-${{ steps.tag.outputs.tag }}-firefox.zip *
          gh release upload \
            ${{ steps.tag.outputs.tag }} \
            better-afreecatv-${{ steps.tag.outputs.tag }}-firefox.zip
          rm *.zip

          git restore manifest.json
          cat manifest.json | jq 'del(.browser_specific_settings) | del(.background.scripts)' | tee manifest.json
          zip -r better-afreecatv-${{ steps.tag.outputs.tag }}-chrome.zip *
          gh release upload \
            ${{ steps.tag.outputs.tag }} \
            better-afreecatv-${{ steps.tag.outputs.tag }}-chrome.zip
