name: tag-release
on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Bump to v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Tag
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(echo ${MESSAGE} | cut -f 3 -d " ")
          echo Tagging ${tag}
          gh release create \
            ${tag} \
            --generate-notes
